name: PHP Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.1', '8.2', '8.3', '8.4' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: posix,sockets,pcntl,openssl,parallel,curl,ev
        env:
          phpts: ts

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --teamcity
